
const isimler=[
    "JALE", 
    "ALİ",
    "MAHMUT",
    "MANSUR KÜRŞAD",
    "GAMZE",
    "MİRAÇ",
    "YÜCEL",
    "KUBİLAY",
    "HAYATİ",
    "BEDRİYE MÜGE",
    "BİRSEN",
    "SERDAL",
    "BÜNYAMİN",
    "ÖZGÜR",
    "FERDİ",
    "REYHAN",
    "İLHAN",
    "GÜLŞAH",
    "NALAN",
    "SEMİH",
    "ERGÜN",
    "FATİH",
    "ŞENAY",
    "SERKAN",
    "EMRE",
    "BAHATTİN",
    "IRAZCA",
    "HATİCE",
    "BARIŞ",
    "REZAN",
    "FATİH",
    "FUAT",
    "GÖKHAN",
    "ORHAN",
    "MEHMET",
    "EVREN",
    "OKTAY",
    "HARUN",
    "YAVUZ",
    "PINAR",
    "MEHMET",
    "UMUT",
    "MESUDE",
    "HÜSEYİN CAHİT",
    "HAŞİM ONUR",
    "EYYUP SABRİ",
    "MUSTAFA",
    "MUSTAFA",
    "UFUK",
    "AHMET ALİ",
    "MEDİHA",
    "HASAN",
    "KAMİL",
    "NEBİ",
    "ÖZCAN",
    "NAGİHAN",
    "CEREN",
    "SERKAN",
    "HASAN",
    "YUSUF KENAN",
    "ÇETİN",
    "TARKAN",
    "MERAL LEMAN",
    "ERGÜN",
    "KENAN AHMET",
    "URAL",
    "YAHYA",
    "BENGÜ",
    "FATİH NAZMİ",
    "DİLEK",
    "MEHMET",
    "TUFAN AKIN",
    "MEHMET",
    "TURGAY YILMAZ",
    "GÜLDEHEN",
    "GÖKMEN",
    "BÜLENT",
    "EROL",
    "BAHRİ",
    "ÖZEN ÖZLEM",
    "SELMA",
    "TUĞSEM",
    "TESLİME NAZLI",
    "GÜLÇİN",
    "İSMAİL",
    "MURAT",
    "EBRU",
    "TÜMAY",
    "AHMET",
    "EBRU",
    "HÜSEYİN YAVUZ",
    "BAŞAK",
    "AYŞEGÜL",
    "EVRİM",
    "YASER",
    "ÜLKÜ",
    "ÖZHAN",
    "UFUK",
    "AKSEL",
    "FULYA",
    "BURCU",
    "TAYLAN",
    "YILMAZ",
    "ZEYNEP",
    "BAYRAM",
    "GÜLAY",
    "RABİA",
    "SEVDA",
    "SERHAT",
    "ENGİN",
    "ASLI",
    "TUBA",
    "BARIŞ",
    "SEVGİ",
    "KALENDER",
    "HALİL",
    "BİLGE",
    "FERDA",
    "EZGİ",
    "AYSUN",
    "SEDA",
    "ÖZLEM",
    "ÖZDEN",
    "KORAY",
    "SENEM",
    "ZEYNEP",
    "EMEL",
    "BATURAY KANSU",
    "NURAY",
    "AYDOĞAN",
    "ÖZLEM",
    "DENİZ",
    "İLKNUR",
    "TEVFİK ÖZGÜN",
    "HASAN SERKAN",
    "KÜRŞAT",
    "SEYFİ",
    "ŞEYMA",
    "ÖZLEM",
    "ERSAGUN",
    "DİLBER",
    "MESUT",
    "ELİF",
    "MUHAMMET FATİH",
    "ÖZGÜR SİNAN",
    "MEHMET ÖZGÜR",
    "MAHPERİ",
    "ONUR",
    "İBRAHİM",
    "FATİH",
    "SEVİL",
    "SÜHEYLA",
    "VOLKAN",
    "İLKAY",
    "İLKNUR",
    "ZÜMRÜT ELA",
    "HALE",
    "YENER",
    "SEDEF",
    "FADIL",
    "SERPİL",
    "ZÜLFİYE",
    "SULTAN",
    "MUAMMER HAYRİ",
    "DERVİŞ",
    "YAŞAR GÖKHAN",
    "TUBA HANIM",
    "MEHRİ",
    "MUSTAFA FERHAT",
    "SERDAR",
    "MUSTAFA ERSAGUN",
    "ONAT",
    "ŞÜKRÜ",
    "OLCAY BAŞAK",
    "SERDAR",
    "YILDIZ",
    "AYDIN",
    "ALİ HALUK",
    "NİHAT BERKAY",
    "İSMAİL",
    "AYKAN",
    "SELÇUK",
    "MEHMET",
    "NEZİH",
    "MUSTAFA",
    "TİMUR",
    "ERHAN",
    "MUSTAFA",
    "MUTLU",
    "MEHMET HÜSEYİN",
    "İSMAİL EVREN",
    "OSMAN ERSEGUN",
    "MEHMET",
    "ELİF",
    "SERKAN",
    "MESUT",
    "MEHMET HİLMİ",
    "ASUDAN TUĞÇE",
    "AHMET GÖKHAN",
    "BAŞAK",
    "CEYHAN",
    "MUHAMMET TAYYİP",
    "ESİN",
    "ZEYNEP GÖKÇE",
    "EVRİM",
    "YASİN",
    "SALİHA",
    "DENİZ",
    "BELGİN",
    "ÖZLEM",
    "GONCA",
    "ESRA",
    "SEÇKİN",
    "ESRA",
    "FATİH",
    "MUSTAFA",
    "FEVZİYE",
    "MUSTAFA ARİF",
    "BİRGÜL",
    "ÖZLEM",
    "ÖZLEM",
    "FUNDA",
    "BERFİN",
    "DEMET",
    "SONAY",
    "SERÇİN",
    "ALMALA PINAR",
    "ÜMİT",
    "SENEM",
    "DENİZ",
    "MÜNEVER",
    "HATİCE",
    "ÖZLEM",
    "ÖZLEM",
    "ALİ SEÇKİN",
    "COŞKUN",
    "ÖZGE",
    "ZELİHA",
    "PINAR",
    "AYBÜKE",
    "HASİBE",
    "GÜRKAN",
    "ZÜHAL",
    "NAZIM",
    "ZEYNEP",
    "OSMAN",
    "AYLA",
    "BEYZA",
    "ELİF",
    "ERAY",
    "DİANA",
    "TUBA",
    "SEMRA",
    "VELAT",
    "BELGİN EMİNE",
    "SİBEL",
    "GÖKMEN ALPASLAN",
    "BENHUR ŞİRVAN",
    "DİLEK",
    "HANDE",
    "ŞAHABETTİN",
    "MİRAY",
    "ZERRİN",
    "İLKNUR",
    "ELİF",
    "MÜMTAZ",
    "TUĞBA",
    "DİLEK",
    "MEHMET BURHAN",
    "FUAT",
    "NİHAL",
    "AYŞEGÜL",
    "SEMA",
    "ZAFER",
    "NURSEL",
    "GÜLPERİ",
    "BİLGE",
    "FATİH",
    "CENGİZ",
    "SİMGE",
    "SEMA NİLAY",
    "EMİNE",
    "RİFAT CAN",
    "SİNAN",
    "LATİFE",
    "MEHMET",
    "NURDAN",
    "MELTEM",
    "ÜLKÜHAN",
    "HASAN",
    "GÜLDEN",
    "SAMET",
    "BERNA",
    "ÖZLEM",
    "NAFİYE",
    "KENAN",
    "SERKAN FAZLI",
    "NURSEL",
    "ABDULLAH",
    "ERGÜL",
    "HASAN",
    "MUSTAFA",
    "SEBAHAT",
    "EMİNE",
    "ERDAL",
    "LEZİZ",
    "BİRSEN",
    "TUBA",
    "AYŞEN",
    "EBRU",
    "TAYFUR",
    "MELTEM",
    "SERHAT",
    "AYCAN ÖZDEN",
    "ELİF",
    "SEVGÜL",
    "SELDA",
    "IŞIL",
    "SİBEL",
    "JÜLİDE ZEHRA",
    "BERİL GÜLÜŞ",
    "İNCİ",
    "ENGİN",
    "GÜLBAHAR",
    "MÜBECCEL",
    "NURDAN",
    "HANDE",
    "ÖZNUR",
    "HANDAN",
    "OSMAN TURGUT",
    "EMİN TONYUKUK",
    "NEJDET",
    "MUSTAFA",
    "GÜLİZ",
    "İPEK",
    "NİHAL",
    "MELDA",
    "DERYA",
    "DEMET",
    "MAHMUT",
    "EMEL",
    "ÖZNUR",
    "SONGÜL",
    "RESA",
    "GAMZE",
    "ÜMİT",
    "DENİZ",
    "MUAMMER MÜSLİM",
    "ÖMER FARUK",
    "TUĞÇE",
    "VELİ ENES",
    "ZAHİDE",
    "NURETTİN İREM",
    "SEDAT",
    "REMZİYE",
    "SİBEL",
    "İLKNUR",
    "YASEMİN",
    "AYLİN",
    "EMEL",
    "EMEL CENNET",
    "ŞAFAK",
    "METİN",
    "SÜLEYMAN",
    "MUKADDES",
    "BARIŞ",
    "MEHMET ALİ",
    "TEVFİK",
    "SERDAR",
    "EMİNE",
    "MÜRŞİT",
    "MUTLU",
    "FEZA",
    "İBRAHİM TAYFUN",
    "SERKAN",
    "AHMET SERKAN",
    "FATMA",
    "BERKER",
    "SERDAR",
    "KUBİLAY",
    "ERKAN",
    "KERİM",
    "İLKNUR",
    "SERKAN",
    "MUSTAFA",
    "RUKİYE",
    "GÖKTEN",
    "SEZGİ",
    "TUĞBA",
    "MURAT",
    "HATİCE",
    "HATİCE EYLÜL",
    "AYŞE GÜL",
    "NEVİN",
    "HABİBE",
    "KEZBAN",
    "AYSEL",
    "TALHA",
    "DUYGU",
    "GÖZDE",
    "FIRAT",
    "EBRU",
    "GÜLEN ECE",
    "SİBEL",
    "FULYA",
    "VEDAT",
    "HARUN",
    "FİLİZ",
    "NURAY",
    "ŞİRİN",
    "ÖZLEM",
    "BURCU",
    "PINAR",
    "HATUN",
    "CEYDA",
    "BURCU",
    "AYŞE",
    "ALPER",
    "FEYZA",
    "HACI MURAT",
    "MÜCELLA",
    "FEYZAHAN",
    "ŞENAY",
    "MERİH",
    "YUSUF",
    "ARDA",
    "EVRE",
    "KONURALP",
    "KIVANÇ",
    "EMİNE",
    "VOLKAN",
    "NİHAT",
    "RENGİN ASLIHAN",
    "EMRE",
    "ARİFE ESRA",
    "SEDAT",
    "MURAT",
    "CEM",
    "ERHAN",
    "ÖMÜR",
    "UMUT CAN",
    "MUSTAFA NAFİZ",
    "DAMLA",
    "MÜSLİM",
    "ABDULKADİR",
    "SAADET",
    "REZZAN",
    "SEDAT",
    "İBRAHİM",
    "LEYLA",
    "TÜLAY",
    "ENDER",
    "YELİZ",
    "ÖZGÜL",
    "HALE",
    "BERÇEM",
    "MUSTAFA",
    "TUBA",
    "SABAHATTİN",
    "ŞAFAK",
    "EVRİM",
    "REŞAT",
    "MUMUN",
    "FUNDA ÖZLEM",
    "NUR",
    "METE",
    "TÜLAY",
    "ÖZLEM",
    "HATİCE NİLDEN",
    "MELTEM",
    "EDA",
    "MELTEM",
    "MUSTAFA",
    "YURDUN",
    "SEMA",
    "TUBA",
    "SERPİL",
    "CENK",
    "TANER",
    "ZEKERİYA",
    "MUHAMMED ALİ",
    "TUĞRUL",
    "YÜCEL",
    "ESMA ÖZLEM",
    "AHMET",
    "SEVDE NUR",
    "SAMİ",
    "GAMZE",
    "GÜLSÜM",
    "SERHAT",
    "BARIŞ",
    "GÜLSEREN",
    "SULTAN",
    "İLKER",
    "DERAM",
    "AHMET",
    "BALA BAŞAK",
    "FEVZİ FIRAT",
    "GÖZDE",
    "FERHAN",
    "İLKER",
    "SALİM",
    "EMİNE",
    "MURAT",
    "ATAKAN",
    "REFİK",
    "MUSTAFA",
    "ÖZGÜR",
    "İKLİL",
    "ZÜHAL GÜLSÜM",
    "MEHTAP",
    "DENİZ",
    "ÜMİT",
    "MEHMET",
    "VOLKAN",
    "İLKNUR",
    "SELÇUK",
    "ÖZLEM",
    "GÖKHAN",
    "METE",
    "HÜMEYRA",
    "PAPATYA",
    "LEVENT",
    "FADİME SEVGİ",
    "ERSEN",
    "ŞULE MİNE",
    "MELİA",
    "ŞERMİN",
    "AYLİA",
    "AHMET EMRE",
    "VEDAT",
    "HALUK",
    "SEZGİN",
    "ZEHRA BETÜL",
    "VOLKAN",
    "ÜNSAL",
    "KORAY",
    "GÜLŞAH",
    "HİCRAN",
    "YUSUF KENAN",
    "YUSUF",
    "ORHAN",
    "FÜSUN",
    "ÖZLEM",
    "MEHMET",
    "SERKAN",
    "İKRAM",
    "ÜLKÜHAN",
    "NUH",
    "İSMAİL",
    "GÜLŞAH",
    "AYKUT",
    "NEŞE",
    "NEZAKET",
    "MUHAMMET DEVRAN",
    "HANDAN",
    "ATİLLA",
    "AYŞEGÜL",
    "PINAR",
    "ARZU",
    "NEŞE",
    "CEYHAN",
    "HASAN SAMİ",
    "MEHMET",
    "SALİH",
    "FERDA",
    "DİLEK",
    "AYHAN",
    "HASAN ULAŞ",
    "SUNA",
    "SELAMİ",
    "SÜREYYA",
    "BURCU",
    "CEM YAŞAR",
    "ÇAĞDAŞ",
    "DOĞAN",
    "AHMET",
    "HATİCE",
    "HAYRİ",
    "GÜHER",
    "SUNA",
    "ARZU",
    "AHMET",
    "AHMET",
    "SEMİH",
    "YUSUF",
    "ALİ",
    "ELİF ÇİLER",
    "ELİF",
    "YETKİN",
    "BURAK",
    "VEYSEL",
    "BURCU",
    "REFAETTİN",
    "AYŞE GÜL",
    "HÜSEYİN KUNTER",
    "EMİNE",
    "EBRU",
    "ESRA NUR",
    "SAMİ",
    "MUSTAFA GÜRHAN",
    "ORHAN",
    "HAÇÇE",
    "MEHMET MURAT",
    "NAZAN",
    "TUĞBA",
    "OĞUZHAN",
    "BERFİN CAN",
    "ÖZGÜR",
    "CİHAN",
    "DERMAN",
    "NİHAL",
    "IŞIN",
    "HATİCE",
    "DİDEM",
    "SUAT",
    "SİMENDER",
    "ADNAN",
    "SEZİN",
    "ŞERAFETTİN",
    "BERRİN",
    "ÖZGÜR",
    "TAYFUR",
    "SERHAT",
    "FUNDA",
    "NESLİHAN",
    "SERVET",
    "EMRE",
    "ORÇUN",
    "FATMA ESİN",
    "DERYA",
    "DUYGU",
    "HÜSEYİN",
    "AYKUT",
    "AYŞE",
    "SEHER ÖZLEM",
    "SEDA",
    "ESRA CAN",
    "EVREN",
    "NİLÜFER",
    "MURAT",
    "YUSUF",
    "MUSTAFA BARAN",
    "GÜNEŞ",
    "FATİH",
    "MEHMET",
    "ORHAN",
    "PINAR",
    "ERHAN",
    "GÜLDEN",
    "LATİFE",
    "SİBEL",
    "FATMA SELCEN",
    "HALİS",
    "YELDA",
    "ZEHRA",
    "MEHMET REŞİT",
    "EMCED",
    "OKAN",
    "ABDULLAH ARİF",
    "ÖZLEM",
    "AYDEMİR",
    "FATİH",
    "AYDIN",
    "BENGÜHAN",
    "AHMET",
    "TOLUNAY",
    "TUĞRA",
    "ÖZGÜR",
    "YUSUF",
    "ÖNDER TURGUT",
    "BARAN",
    "SEYHAN",
    "ZEKİ",
    "KADİR",
    "MURAT",
    "İHSAN",
    "DEMİR",
    "MUHAMMET MURAT",
    "MUHAMMED",
    "BAHADIR",
    "İLHAN",
    "YILDIRIM",
    "OĞUZ KAAN",
    "EFTAL MURAT",
    "GÖKAY",
    "FATİH RIFAT",
    "NURAN",
    "HABİL",
    "ÖMER ÖZKAN",
    "SELMA",
    "NURETTİN",
    "AHMET",
    "UTKU",
    "SÜLEYMAN",
    "CAN",
    "ONUR KADİR",
    "FİLİZ",
    "CANSU SELCAN",
    "ABDULLAH",
    "NESLİHAN",
    "SEDA ELÇİM",
    "KÜBRA",
    "HÜSEYİN",
    "BELMA",
    "MÜCAHİT",
    "CEYHUN",
    "GÜLTEKİN  GÜNHAN",
    "HANDE",
    "GÜLHANIM",
    "ÖMER",
    "ZİYA",
    "ÇAĞRI",
    "SERKAN",
    "LEVENT",
    "İSA",
    "CEM",
    "HÜSEYİN",
    "CEMİLE ÇİĞDEM",
    "MAHMUT",
    "ÖNDER",
    "RAŞAN",
    "İSMAİL YAVUZ",
    "ÖMER",
    "KENAN SELÇUK",
    "EMRE",
    "SERDAR",
    "SONER",
    "ENVER",
    "MUHLİS",
    "TİMUR",
    "LEMAN",
    "ELA",
    "CEMİL",
    "BURCU",
    "SALİHA SANEM",
    "ZELİHA",
    "ALEVTİNA",
    "ARZU",
    "MEHMET",
    "BİREYLÜL",
    "AYSEL",
    "ÖZGÜL",
    "SIDIKA",
    "TUNA",
    "ÖVGÜ ANIL",
    "EMİŞ",
    "NİLGÜN",
    "ELİF",
    "SEBİHA",
    "YUSUF ALPER",
    "IŞIL",
    "AYŞEGÜL",
    "TÜMAY",
    "ZERİN",
    "MEHMET",
    "FATMA ECE",
    "AHMET",
    "NEVROZ",
    "SEMA",
    "GAMZE PINAR",
    "FATMA",
    "MELTEM HALE",
    "SELMA",
    "İBRAHİM",
    "ASLIHAN",
    "FİLİZ",
    "BİLGİ",
    "TUĞBA",
    "HÜSEYİN",
    "EVREN",
    "FERDİ",
    "BURÇİN",
    "BARIŞ",
    "BAVER",
    "MAHMUT",
    "EMRAH KEMAL",
    "MURAT",
    "MEHMET ÖZER",
    "GÖKAY",
    "NECİP",
    "ERKAN",
    "ÜMİT",
    "GANİM",
    "BARAN",
    "FATİH",
    "SANCAR",
    "MUSTAFA KEMAL",
    "DURAN",
    "HASAN",
    "GÖRKEM",
    "ALİ OZAN",
    "VELİ ÇAĞLAR",
    "İRFAN",
    "SEYFİ CEM",
    "CÜNEYT",
    "ALİ",
    "FIRAT",
    "MUHAMMED TAHA",
    "BURAK",
    "MUSTAFA",
    "NİZAMETTİN",
    "RECEP GANİ",
    "ARZU",
    "MAHMUT NURİ",
    "GÜNAY",
    "BESTE",
    "CEM",
    "EMRAH",
    "HALİL İBRAHİM",
    "ESEN İBRAHİM",
    "MELİKE",
    "MÜRSEL",
    "KORAY",
    "UMUT SİNAN",
    "İBRAHİM BARIŞ",
    "BURHAN",
    "MUSTAFA KÜRŞAT",
    "SERDAR BORA",
    "FUAT",
    "ELİF",
    "SİBEL",
    "ADEM",
    "CEM İNAN",
    "GÖKTEKİN",
    "DİLARA",
    "SEDA",
    "CUMHUR",
    "HALUK",
    "PINAR",
    "AYKUT",
    "ÖYKÜ",
    "BAŞAK",
    "ÖMER",
    "SERHAN",
    "SULTAN",
    "MİNE CANSU",
    "SUAT",
    "ÇİĞDEM",
    "HANDE",
    "UMUT SEDA",
    "EVRİM",
    "DİCLE",
    "İREM",
    "FATMA",
    "İLKNUR",
    "CEMİLE AYŞE",
    "FEYZA",
    "MUAMMER",
    "EBRU",
    "DİNÇER AYDIN",
    "AYŞE AHSEN",
    "PINAR",
    "SÜREYYA BURCU",
    "MARİA",
    "SEÇİL",
    "BARIŞ",
    "ŞAHİNDE",
    "MEHMET",
    "NEVRİYE",
    "NİLAY",
    "RÜŞTÜ",
    "ASLI",
    "TANSU",
    "ASLIHAN",
    "NURCAN",
    "DEMET",
    "ERDEM",
    "BETÜL EMİNE",
    "ÇETİN",
    "PINAR",
    "RASİM",
    "AHMET",
    "ZEHRA",
    "SELİM",
    "DENİZ",
    "MESUT",
    "AYSEL",
    "MÜMÜNE",
    "DUÇEM",
    "YAKUP",
    "ERCAN",
    "MEHMET GÖKÇE",
    "ATİLLA SÜLEYMAN",
    "MERAL",
    "NURDAN",
    "SEÇİL",
    "ELİF",
    "HASAN BİLEN",
    "NİLAY",
    "HİLAL",
    "MUSTAFA",
    "ŞEYMA MELİHA",
    "MÜJDAT",
    "BURCU",
    "ARİF",
    "AYŞE",
    "HACİ HALİL",
    "IŞIK",
    "SERAY",
    "SERHAT BURKAY",
    "EMİN",
    "ÇAVLAN",
    "ŞEREF CAN",
    "KADİR",
    "MÜBERRA",
    "AYŞE",
    "HASAN",
    "SAVAŞ",
    "AYŞE NUR",
    "SÜLEYMAN",
    "DUYGU",
    "HACI MEHMET",
    "MEHTAP",
    "ERKAN",
    "SEMİNE",
    "ELİF",
    "RAMAZAN",
    "AHMET EMRE",
    "SERKAN",
    "DENİZ",
    "MİNE",
    "FATİH",
    "İREM",
    "ENDER",
    "YASEMİN",
    "SEMA",
    "MUSTAFA ULAŞ",
    "ALİ",
    "EMİNE",
    "TÜLAY",
    "BİRSEN",
    "GÜLSEN",
    "TUBA",
    "HAYRİYE",
    "BAHADIR",
    "SEZEN",
    "EDİP GÜVENÇ",
    "MEHTAP",
    "FİLİZ",
    "EYLEM",
    "RAMAZAN",
    "BİLGİN",
    "ESRA",
    "ATİYE MELTEM",
    "METİN",
    "ÖZLEM",
    "OSMAN",
    "AYŞE",
    "HİLAL",
    "YAVUZ",
    "ÖZLEM",
    "AYŞE",
    "MUSTAFA",
    "ASUMAN",
    "ÖMER",
    "ŞENAY",
    "GÜLNAME",
    "ÖZLEM",
    "BETÜL",
    "EMİNE DİLEK",
    "ZELİHA",
    "ESİN SEREN",
    "FİLİZ",
    "ULAŞ",
    "HALE",
    "ADEM",
    "İLKER",
    "ERHAN",
    "FARUK",
    "İBRAHİM",
    "SERKAN",
    "MAHMUT ESAT",
    "ERAY",
    "OKTAY",
    "DENİZ",
    "OSMAN",
    "İZZET",
    "İHSAN",
    "URAL",
    "ARİF",
    "AZİZ",
    "FUAT ERNİS",
    "HAKAN",
    "MUZAFFER OĞUZ",
    "MAHİR",
    "TAYYAR ALP",
    "EREM",
    "CİHAN",
    "MEHMET",
    "ÜMİT",
    "MEHMET",
    "YASEMİN",
    "CEYDA",
    "FATIMA İLAY",
    "NİLAY",
    "HURİYE",
    "MERVE",
    "ŞEYMA",
    "SELAHATTİN",
    "İLKER",
    "ÖMER",
    "SÜLEYMAN",
    "TAYFUN",
    "ESER",
    "MEHMET CİHAT",
    "İSMAİL",
    "ABDULLAH",
    "MURAT",
    "MUSTAFA",
    "AYDOĞAN",
    "HAMDİYE",
    "KERİME RUMEYSA",
    "MELAHAT",
    "UYSAN",
    "EMRAH",
    "HAYRİ ÜSTÜN",
    "MURAT",
    "HÜSEYİN SAİD",
    "SELİM",
    "ZEKERİYA",
    "FATİH",
    "DERYA",
    "NEVAL",
    "SEZER",
    "ÖZGE",
    "HATİKE",
    "ÖZGÜR",
    "ŞAFAK",
    "AHMET TUNÇ",
    "ÖZDEN",
    "OKAN",
    "RAZİYE DAMLA",
    "MAHMUT",
    "LALE",
    "EYÜP",
    "DERYA",
    "SELAHATTİN",
    "ZEKİ",
    "HÜSEYİN",
    "MELEK",
    "BİNNUR",
    "ONUR SALİH",
    "ERKİN",
    "MURAT",
    "ERHAN",
    "BURAK",
    "AYŞE CEREN",
    "NUMAN",
    "ÖZLEM",
    "ÜZEYİR",
    "CAN",
    "MUSTAFA",
    "KORHAN",
    "ALPER",
    "FUNDA",
    "HAMZA",
    "MUSTAFA RAŞİD",
    "YUSUF",
    "MELİKE",
    "ŞÜKRÜ",
    "KASIM",
    "GÖKSEL",
    "HİKMET",
    "ASIM",
    "ÜMRAN",
    "TEKİN",
    "MURAT",
    "HACER",
    "BERAY",
    "HANIM",
    "EDA",
    "NURAY",
    "ÖMER FARUK",
    "FERHAT",
    "OĞUZ",
    "BENGÜ",
    "AHMET MERT",
    "PINAR",
    "EMRE",
    "KÜBRA",
    "SELÇUK",
    "ŞENOL",
    "ORHAN",
    "MÜMÜN FATİH",
    "MURAT",
    "MERT",
    "KADİR",
    "KAAN SUAT",
    "ERCAN",
    "GÖKHAN",
    "DENİZ",
    "CİHAN",
    "CEM",
    "ALİŞAN",
    "ALİ SAİP",
    "ABİDE MERVE",
    "YUSUF",
    "ÖMER",
    "SERDAR",
    "YÜKSEL",
    "AHMET",
    "MAHMUT",
    "BURAK",
    "YASEMİN",
    "İBRAHİM FUAT",
    "MUSTAFA",
    "BİLGE MERVE",
    "AHMET CEVDET",
    "SEHER",
    "MEHMET DENİZ",
    "SAMET",
    "SAMET SANCAR",
    "ŞULE",
    "SELİM",
    "KADİR",
    "CAHİT",
    "HAYRUNNİSA",
    "UĞUR",
    "RESUL",
    "MUSTAFA BUĞRA",
    "İSHAK",
    "ESRA",
    "SANEM GÖKÇEN MERVE",
    "EZGİ",
    "MUSTAFA GÜVENÇ",
    "OĞUZ KAĞAN",
    "ESMA",
    "ÖMER AYKUT",
    "MEHMET ŞİRİN",
    "OSMAN",
    "AHMET",
    "NAİL",
    "İREM",
    "ELA",
    "BAHRİ",
    "ALİ RIZA",
    "ADEM",
    "MEHMET",
    "BAYRAM FURKAN",
    "HALİL",
    "KÜBRA",
    "SEFA",
    "MEHTAP",
    "FATİH",
    "BERKAN",
    "HÜSEYİN",
    "VOLKAN",
    "ŞEBNEM",
    "TUBA",
    "AYHAN",
    "ENNUR",
    "ALİ RIZA",
    "FATİH",
    "GÖZDE",
    "SEVİL",
    "EDA",
    "HATİCE",
    "ZARİFE",
    "BURAK",
    "İREM",
    "KÜBRA",
    "EMİNE",
    "DİLEK",
    "TUBA",
    "HALİL",
    "ESER",
    "EBUBEKİR ONUR",
    "MEHMET VEYSEL",
    "BURCU",
    "AYŞEGÜL",
    "DERYA SEMA",
    "ÇAĞLA",
    "KADİR",
    "BURAK",
    "MELİKE",
    "BAYRAM",
    "AYŞEGÜL",
    "TUĞBA",
    "MEHMET",
    "ELİF",
    "TÜRKER",
    "SEMİH",
    "HATİCE",
    "CANSU",
    "SERHAT",
    "TANER",
    "İDRİS",
    "SEVİNÇ",
    "FERİDE",
    "EVREN",
    "TUĞBA",
    "MUHAMMED MUCAHİD",
    "HİLAL",
    "DİLEK",
    "NAZLI",
    "ŞİFA",
    "GÜLÇİN",
    "KEZBAN",
    "YELDA",
    "SEDA",
    "CEYLAN",
    "BURAK",
    "UĞUR",
    "ŞEYMA",
    "SELMA",
    "EMRE",
    "MUHAMMED FATİH",
    "AHMET",
    "HASAN",
    "RUKİYE",
    "ADİL",
    "MUSTAFA",
    "MUSTAFA ASIM",
    "METİN",
    "CEREN",
    "SÜLEYMAN",
    "MELİKE",
    "TUĞBA",
    "ÇAĞRI",
    "BURHANETTİN",
    "İBRAHİM",
    "YUNUS EMRE",
    "KADİR",
    "MEHMET",
    "İLKER",
    "GÖKHAN",
    "KEMAL KÜRŞAT",
    "AHMET",
    "ZEHRA",
    "AZİZ",
    "İSA",
    "GÖKHAN",
    "BARIŞ",
    "MEHMET SUPHİ",
    "ASİYE BURCU",
    "ZEYNEP",
    "YÜKSEL UĞUR",
    "VOLKAN",
    "UFUK",
    "TUĞBA",
    "SELİM",
    "SELÇUK",
    "SALİHA DİLEK",
    "ÖZKAN",
    "ÖVÜNÇ",
    "OSMAN",
    "NUR ALEYNA",
    "MUHAMMED FURKAN",
    "MEHMET VEHBİ",
    "MEHMET İKBAL",
    "MEHMET",
    "LEYLA",
    "İZZETTİN",
    "İSMAİL",
    "İSMAİL",
    "İHSAN BURAK",
    "İBRAHİM",
    "HİLAL",
    "HAYRİYE",
    "GİZEM",
    "ESİN",
    "ERCAN",
    "ENES TAHİR",
    "DİDEM",
    "DENİZ",
    "BUĞRA",
    "BİLGİN",
    "ALİ MUHARREM",
    "ALİ",
    "ADEM",
    "ADEM",
    "IŞIL",
    "YUSUF",
    "MUSTAFA",
    "HÜSEYİN",
    "EZEL",
    "EMİNE",
    "ELİF CEREN",
    "AYŞE GİZEM",
    "DEMET",
    "DİDEM AYŞE",
    "ESER",
    "AYŞE GÜLÇİN",
    "HACER",
    "FERAT",
    "ZEYNEP",
    "KIYMET",
    "ASLAN",
    "ALİ",
    "GİZEM",
    "CUMA",
    "MEHTAP",
    "HAMDİ",
    "ORHAN",
    "NURİ ANIL",
    "SEMRA",
    "ÖKKEŞ",
    "VEYSEL",
    "ŞERİFE YASEMİN",
    "MEHMET",
    "MEHMET",
    "TOLGA",
    "OĞUZHAN",
    "MUSTAFA",
    "MAHSUM",
    "İSMAİL",
    "MEHMET",
    "PERVİN",
    "MURAT",
    "SALİM",
    "YUNUS",
    "VEYSEL",
    "ÖMER",
    "AHMET",
    "AYDIN",
    "ABDULKADİR",
    "AHMET",
    "AYŞEGÜL",
    "AZİZ",
    "ABDULLAH",
    "ABDULLAH",
    "YILDIRIM",
    "AYŞEGÜL",
    "İBRAHİM",
    "SİBEL",
    "MUZAFFER",
    "MUHAMMED YUSUF",
    "HAMZA",
    "HAKAN",
    "NESRİN",
    "EMRAH",
    "KEZİBAN",
    "MEHMET ALİ",
    "MELİKE ELİF",
    "BURHAN",
    "CEVAHİR",
    "CİHAN",
    "EMRAH",
    "MEHMET ALİ",
    "FATİH",
    "MAHMUT",
    "FATİH",
    "DAVUT",
    "EDA",
    "PELİN",
    "SALİH",
    "YUSUF ZİYA",
    "ZERİN",
    "ÖZKAN",
    "YUSUF",
    "UMUT",
    "EMRAH",
    "ŞEYHMUS",
    "MERT METİN",
    "MUKADDES",
    "HAZAN",
    "HALİM",
    "MEHMET AKİF",
    "AYCAN",
    "CEMİL",
    "BERNA",
    "AHMET",
    "HÜSEYİN",
    "ERKAN",
    "HAKAN",
    "BAYRAM",
    "RUMEYSA",
    "ÇİLE",
    "VEYSİ",
    "ZUHAL",
    "YÜCEL",
    "ESMERALDA",
    "NİLÜFER",
    "BURÇHAN",
    "VOLKAN",
    "SELCEN",
    "MUSTAFA",
    "HATİCE",
    "BURCU",
    "AHMET BURAK",
    "BÜLENT",
    "MÜCADİYE",
    "SONGÜL",
    "IŞIK MELİKE",
    "MEHMET RAŞİT",
    "AYHAN",
    "SERDAR",
    "ERKAN",
    "EMRAH",
    "ERDAL",
    "RAHİME",
    "GÜLDEN SİNEM",
    "İHSAN",
    "ABDUL AZİM",
    "ÖZTAN",
    "ŞENOL",
    "MEHMET HAZBİN",
    "İSMAİL ŞENOL",
    "BORA",
    "HAMZA",
    "SEDA",
    "FATİH",
    "UĞUR",
    "KEMAL",
    "ADİL",
    "MAZLUM",
    "CEM ATAKAN",
    "VOLKAN",
    "MUHAMMED",
    "ERDEM",
    "FATMA",
    "HATİCE",
    "MEHMET EVREN",
    "ATACAN",
    "FATMA",
    "ŞADİ",
    "GÜLCAN",
    "MERYEM",
    "KAMERCAN",
    "ESRA",
    "ŞERİFE SEÇİL",
    "ZEHRA",
    "VAZİR AKBER",
    "ZEYNEP",
    "ALİ SAİD",
    "MURAT",
    "UTKU",
    "SAİD",
    "İRFAN",
    "HALİME",
    "ÜMMÜ GÜLSÜM",
    "ŞAFAK",
    "BETÜL",
    "BAŞAK",
    "ZEYNEP EZGİ",
    "VASFİYE",
    "ERDEM",
    "İBRAHİM",
    "AYŞE",
    "MEHMET VEHBİ",
    "FATMA",
    "EMEL",
    "ADEM",
    "ESEN",
    "HACI KEMAL",
    "EMRE",
    "ÖZGÜR",
    "OSMAN",
    "ÇETİN",
    "SONGÜL",
    "MUSTAFA",
    "ÖZLEM",
    "ZAFER",
    "FATİH",
    "MAKBULE SEDA",
    "FATMA BEGÜM",
    "TUĞBA",
    "OSMAN",
    "SİNEM",
    "ANIL",
    "KEMAL",
    "EREN",
    "BİLAL BARIŞ",
    "İBRAHİM",
    "ATILGAN",
    "BERNA",
    "SERAP",
    "BEKİR",
    "EYÜP",
    "EGEMEN",
    "ALİ",
    "YÜCEL",
    "TANER",
    "VAHDETTİN TALHA",
    "TOLGAHAN",
    "MUKADDER",
    "ENGİN",
    "SERTAÇ",
    "CİHAN",
    "PINAR",
    "AYŞE",
    "UĞURAY",
    "MUSTAFA",
    "EDA",
    "ELİF",
    "TAYLAN UĞUR",
    "ABİDİN",
    "BULUT",
    "CUNDULLAH",
    "ADNAN",
    "ERSİN",
    "ERHAN HÜSEYİN",
    "OĞUZ",
    "HAYRİ",
    "NURİ",
    "SELMA",
    "ESİN",
    "YAKUP İLKER",
    "AHMET",
    "ABDULLATİF",
    "FATİH",
    "ÖZLEM",
    "İNANÇ",
    "HALİL İBRAHİM",
    "ÖZGE",
    "HASAN",
    "PINAR",
    "AYŞE",
    "AYŞE",
    "HALİL CAN",
    "CEM ÖZGÜR",
    "SEDA",
    "UMUT",
    "VOLKAN ONUR",
    "EMRAH",
    "NAGİHAN",
    "HÜSEYİN",
    "MEHMET DİRİM",
    "MİNE",
    "GİZEM",
    "ÖMER",
    "TUĞBA",
    "MERVE",
    "YÜCE",
    "AYŞE PINAR",
    "AHMET CAN",
    "MERVE",
    "EMRE",
    "ERDİNÇ",
    "NİLAY",
    "BUŞRA",
    "ZÜHAL",
    "CAFER",
    "İLKER",
    "TURAN",
    "RECEP",
    "EBRU",
    "ÖMER FARUK",
    "MEHMET NURİ",
    "HİLAL",
    "NURHAN",
    "YASEMİN",
    "NAGİHAN",
    "ALİ KEMAL",
    "PINAR",
    "GİZEM",
    "UYGAR",
    "SEFA",
    "NURULLAH",
    "GİZEM",
    "SEVAL",
    "ŞERİF",
    "BERFU",
    "SEMİH",
    "SIDDIKA",
    "TUĞBA",
    "İRFAN YILDIRIM",
    "FAHRİ",
    "CANSU",
    "PETEK",
    "ELİF",
    "CEM",
    "EMRAH",
    "BÜŞRA",
    "NAFİZ",
    "ŞEYMA",
    "EKREM",
    "YASEMİN",
    "AYŞE",
    "ÇAĞRI",
    "MEHMET",
    "ÖMER GÖKHAN",
    "REYHAN",
    "HÜSEYİN",
    "ÖZGE",
    "DERYA",
    "MUSTAFA",
    "ESMA",
    "ÖZLEM",
    "GÖZDE",
    "SELİM",
    "EMİNE",
    "ÇİĞDEM",
    "ŞERİFE EZGİ",
    "NEFİSE",
    "TAYFUN",
    "PELİN",
    "ÖZGE",
    "KADER",
    "BELGİN",
    "ABDULAZİZ",
    "EMEL",
    "NUR",
    "BURCU",
    "CEYDA",
    "VEHBİ",
    "RAHİME",
    "ALİ",
    "DENİZ",
    "MUHAMMED",
    "EMRE",
    "HASAN",
    "ÜBEYDULLAH",
    "EYÜP GÖKHAN",
    "KÜBRA",
    "İTİBAR",
    "MUSTAFA ABDULLAH",
    "TUBA",
    "NURDAN",
    "HATİCE",
    "BÜŞRA",
    "ZEHRA",
    "CANAN",
    "OSMAN BİLGE",
    "TUBA",
    "FARİS",
    "AYHAN",
    "TURĞUT",
    "ONUR",
    "MERVE",
    "HİDAYET",
    "TUBA",
    "ABDULKERİM",
    "MUHAMMED RIZA",
    "DİLEK",
    "ARDA NERMİN",
    "FAİK",
    "HALİL",
    "HASAN HÜSEYİN",
    "SEMA",
    "MUSA",
    "AYŞEGÜL",
    "BÜŞRA",
    "ZEYNEP",
    "METİN",
    "CİHAN",
    "MERAL",
    "HİLAL",
    "DİDEM",
    "İSMAİL",
    "HASAN CIVAN",
    "MEHMET AKİF",
    "FATİH",
    "CEM",
    "YUSUF",
    "HÜSEYİN",
    "TUBA",
    "TAYFUN",
    "MUSTAFA",
    "HASAN",
    "RUKİYE ÖZDEN",
    "MEHMET",
    "ESRA",
    "HASAN",
    "MUSTAFA CİHAD",
    "EYÜP",
    "MURAT",
    "İBRAHİM HALİL",
    "SEDAT",
    "MEHMET",
    "HÜSEYİN",
    "MURAT",
    "HACI",
    "AYŞE FULYA",
    "FAİK",
    "RAMAZAN",
    "MEHMET",
    "SAVAŞ",
    "AYHAN",
    "NAİME SILA",
    "RIFAT",
    "MURAT",
    "FİKRİ",
    "HASAN",
    "YURDAGÜL",
    "MUHAMMET MUSTAFA",
    "ERCAN",
    "TUĞBA",
    "MEHTAP",
    "HAMİT",
    "FERİT",
    "DENİZ",
    "MUSTAFA",
    "ŞAHİKA",
    "SERDAR",
    "TAHSİN BATUHAN",
    "ONUR",
    "MURAT",
    "EMİNE AYÇA",
    "İLYAS",
    "ECE",
    "MUSTAFA",
    "MURAT",
    "AHMET ÇAĞRI",
    "NİLGÜN",
    "MUSTAFA",
    "ERHAN",
    "VEYSEL",
    "HAKAN",
    "FATİH",
    "BARIŞ",
    "ANDAÇ",
    "ŞENOL",
    "HASAN",
    "KEMAL",
    "CEYHUN",
    "ABDÜLSAMET",
    "İBRAHİM",
    "AHMET",
    "SERPİL",
    "ÜMMÜGÜLSÜM",
    "YAVUZ",
    "SÜHEYLA AYÇA",
    "ÖZGE",
    "TUBA",
    "MERT",
    "ÖZGÜR",
    "MELİHA ESRA",
    "BETÜL",
    "ABDULLAH",
    "SİNAN",
    "GÜNDEM",
    "KEZİBAN",
    "DERYA",
    "OĞUZ",
    "BEDRİ",
    "MEHMET",
    "EMRE",
    "ÜMİT",
    "HALİL İBRAHİM",
    "ÖZGE",
    "HAZEL",
    "FATMA BETÜL",
    "MUSTAFA",
    "AHMET BİLGEHAN",
    "HİKMET EKİN",
    "EMİN",
    "YİĞİT",
    "ABDULSAMET",
    "PINAR",
    "MUSACİDE ZEHRA",
    "BURAK",
    "TUĞÇE",
    "MAHMUT BAKIR",
    "ELİF TUĞÇE",
    "EKİN",
    "ASLIHAN ESRA",
    "İSMAİL MİKDAT",
    "UFUK",
    "MEHMET NURİ",
    "BİLGE",
    "ELİF AYŞE",
    "ERKAN SABRİ",
    "İREM",
    "BÜŞRA SULTAN",
    "MUSTAFA ALİCAN",
    "AYBEGÜM",
    "NEFİSE",
    "ZEKERİYA ERSİN",
    "AHMETCAN",
    "ABDURRAHMAN FUAT",
    "ZEYNEP",
    "FATİH",
    "ÇAĞDAŞ",
    "UĞURAY",
    "SARE",
    "ONUR",
    "SERAP",
    "MURAT",
    "EMİNE",
    "MUSTAFA",
    "BAHADIR",
    "ZEYNEP",
    "GÖZDE KÜBRA",
    "BURAK",
    "MEHMET",
    "MUHAMMED HASAN",
    "İSMAİL",
    "SAYGIN",
    "GÖKHAN",
    "ALPER",
    "ÇAĞLAR",
    "CEMAL",
    "HÜSEYİN ONUR",
    "CEMRE",
    "MELTEM",
    "CEYHUN",
    "ASLI",
    "İBRAHİM",
    "GÖZDEM",
    "HİLAYDA",
    "HASRET",
    "ŞEBNEM",
    "ONUR",
    "CAN",
    "AYŞEGÜL",
    "EMİNE",
    "PELİN",
    "ARMAN",
    "MERVE",
    "GAMZE",
    "ALİŞAN",
    "ERDEM",
    "ENES",
    "ORGÜL DERYA",
    "BAŞAK",
    "HASAN KADİR",
    "ŞADİYE SELİN",
    "CEREN",
    "ELİFCAN",
    "SEVAL",
    "GÖKÇEN",
    "ÖMER FARUK",
    "ALİ HASAN",
    "MUSTAFA",
    "KÜBRA",
    "HACI HASAN",
    "GÖKHAN",
    "MERİÇ",
    "İREM",
    "MAHMUT SAMİ",
    "MURAT",
    "SÜLEYMAN SERDAR",
    "NİHAN",
    "HANİFE TUĞÇE",
    "ŞULE",
    "ERTAN",
    "MUHAMMED",
    "ÇAĞDAŞ",
    "ALİ",
    "YUSUF",
    "HATUN",
    "İBRAHİM",
    "MEHMET YAVUZ",
    "MEHMET",
    "ERTAN",
    "SÜMEYRA",
    "FATMA EFSUN",
    "RAMAZAN",
    "MEHMET ALİ",
    "BERKAN",
    "DAVUT",
    "YAVUZ SELİM",
    "İBRAHİM",
    "OKAN",
    "MEHMET",
    "MERT",
    "EMRAH",
    "BURAK",
    "ALAADDİN",
    "İDRİS BUGRA",
    "KÜBRA",
    "AYŞEGÜL",
    "MERVE NUR",
    "SUNA",
    "ELZEM",
    "ABDURRAHMAN",
    "BURAK",
    "MİHRİMAH SELCEN",
    "RABİA",
    "MERİÇ",
    "DERYA",
    "SERKAN",
    "CEYDA",
    "AYŞENUR",
    "MEHMET AKİF",
    "TUĞBA",
    "SERHAT",
    "BAYRAM",
    "MEHMED UĞUR",
    "DAMLA",
    "MUSTAFA",
    "VEYSEL",
    "AHMET SERKAN",
    "GÖKHAN",
    "ABDULSELAM",
    "MEHMET YILDIRIM",
    "HÜSEYİN",
    "BİLAL",
    "YAKUP",
    "GÜLLÜ SELCEN",
    "VEHBİ",
    "DİLAN",
    "ÖMER FARUK",
    "EMRE",
    "MEVLÜT",
    "NEBİL",
    "SIDIKA",
    "FATMA",
    "MARUF",
    "FIRAT",
    "EBRU",
    "MAHMUT",
    "PINAR",
    "ALİ",
    "OSMAN",
    "HİLAL",
    "NİLGÜN",
    "BARIŞ",
    "ERKAN",
    "CİHAN",
    "ÖMER",
    "BEGÜM",
    "SÜLEYMAN",
    "ÖMER",
    "ELİF",
    "MEHMET ZİYA",
    "HAKAN",
    "AHMET SERCAN",
    "BİŞAR",
    "MUSTAFA",
    "NUR",
    "SERKAN",
    "ELİF",
    "HALİL İBRAHİM",
    "EMİNE",
    "FATİH MEHMET",
    "EREN",
    "AYTAÇ",
    "ENGİN",
    "YURDAGÜL",
    "FULYA",
    "YASEMİN",
    "ETHEM",
    "YASİN",
    "METİN",
    "ELİF",
    "FERAT",
    "YUSUF",
    "CİHAN",
    "MUHAMMED",
    "GÜLŞEN",
    "ABDULMELİK",
    "MERVE",
    "ALİ",
    "YASEMİN",
    "MUHAMMET BAĞBUR",
    "YUSUF ZİYA",
    "ERDAL",
    "MURAT",
    "MERVE",
    "RAMAZAN",
    "GÜL",
    "BEGÜM",
    "ORHAN UYGAR",
    "HASAN",
    "SEMA",
    "GÜNEŞ",
    "BEYZA",
    "FIRAT",
    "YİĞİT",
    "MUHSİN",
    "HAMZA",
    "SABAHATTİN",
    "EMİN",
    "AHMET ÇAĞRI",
    "NAZLI",
    "MEHMET",
    "GÖKSEL",
    "BAŞAK",
    "HASAN YAVUZHAN",
    "GÖKHAN",
    "MUHAMMED SAMİ",
    "ENGİN",
    "EBRU",
    "METANET MEHRALİ",
    "EZGİ GİZEM",
    "NESLİHAN",
    "İLYAS",
    "SERKAN",
    "MEHMET SELAHATTİN",
    "MUSTAFA",
    "MEHMET",
    "CİHAN",
    "MURAT",
    "KASIM",
    "RAHİME MERVE",
    "OZAN",
    "ÖZKAN",
    "ZAFER",
    "SENAN",
    "BEDREDDİN",
    "MURAT",
    "ZEYNALABİDİN",
    "CAHİT",
    "DENİZ",
    "MEHMET EMRAH",
    "ESRA",
    "TUNCAY",
    "HÜSEYİN",
    "YİĞİT",
    "BÜNYAMİN",
    "PERVER",
    "ERDEM",
    "ÖMER",
    "SERHAT",
    "EMRE MERTER",
    "ABDÜLKADİR",
    "ENGİN",
    "NURULLAH",
    "ABDULLAH",
    "MEHMET",
    "HASAN",
    "AHMET MELİH",
    "ÖKKEŞ YILMAZ",
    "BURAK",
    "TOLGAHAN",
    "SÜLEYMAN",
    "SUAT",
    "ONUR",
    "MURAT VOLKAN",
    "OSMAN",
    "ALPER",
    "ERHAN",
    "AKIN",
    "ALİ",
    "ÖMER",
    "MUSTAFA",
    "FATMA DUYGU",
    "TÜRKER",
    "HASAN",
    "MUSTAFA TURAN",
    "ERGÜN",
    "ÖZLEM",
    "NİMET",
    "NİHAT",
    "SERHAT",
    "RAHMİ TUNA",
    "NEZİR",
    "YUSUF EMRE",
    "SERDAR",
    "RUKİYE",
    "HACI ÖMER",
    "ÇAĞLA",
    "ÜMİT",
    "MEHMET FATİH",
    "NAZIM",
    "HATİCE",
    "SİDAR",
    "MEHMET",
    "ALİ BURÇ",
    "YUNUS",
    "ÇAĞRI",
    "SİNAN DİNÇER",
    "AYSUN",
    "MUSTAFA",
    "İLKER",
    "PINAR",
    "MAHİR",
    "CEBRAİL",
    "RAMAZAN",
    "SELAHATTİN",
    "NEVİN",
    "MEHMET NEDİM",
    "YASİN",
    "BURHAN",
    "SEVCAN",
    "OSMAN SALİH",
    "MAHMUT EMRE",
    "TEYFİK",
    "SERTAÇ",
    "HALİM",
    "AYSU",
    "EMRE",
    "GİZEM",
    "ASUMAN",
    "GÖKÇE",
    "ZEHRA",
    "ORKUN",
    "SAVAŞ",
    "SELİM",
    "MURAT",
    "ERHAN",
    "FATİH",
    "ÖMER FARUK",
    "ZÜHRE",
    "AHMET",
    "ASENA",
    "EMRE",
    "İSMAİL",
    "MEHMET FURKAN",
    "HABİP",
    "İSMAİL",
    "ENDER",
    "HAKAN",
    "NURGÜL",
    "BURCU",
    "SELÇUK",
    "MAHMUT BURAK",
    "MURAT",
    "İLKER",
    "NİMET DİDEM",
    "NİHAL",
    "ŞÜKRİYE TUĞÇE",
    "REŞİT VOLKAN",
    "SELİM OZAN",
    "HASAN",
    "ZEYNEP",
    "SERKAN",
    "AHMAD TAHER",
    "HÜSEYİN",
    "ZAFER",
    "RAMAZAN",
    "SELKAN MURAD",
    "CANSEN",
    "KAMİL",
    "YÜCEL",
    "DERYA",
    "YASEMİN",
    "TOLGA",
    "ABDULKADİR",
    "ALİ",
    "ÖZEN",
    "FATMA",
    "MUSTAFA",
    "HAMZA",
    "MURAT",
    "CÖMERT",
    "HÜLYA GÖZDE",
    "BERK",
    "AHMET FURKAN",
    "YUSUF",
    "EMRAH",
    "EMRE",
    "ABDULSEMET",
    "EYLEM",
    "İSMAİL",
    "ÇAĞLAR",
    "YASEMİN",
    "MELTEM",
    "TOLGA CAN",
    "EMRE",
    "MUSTAFA",
    "EMİR MURAT",
    "FUNDA",
    "ELİF NUR",
    "NİLAY",
    "AHMET ÇAĞRI",
    "MERVE SETENAY",
    "SAMET",
    "ERDEM CAN",
    "SERKAN",
    "ÖZNUR",
    "ÖZNUR",
    "İSMAİL",
    "RAMAZAN",
    "FATİH",
    "ŞUAYIP",
    "ALİ",
    "SULTAN",
    "EMRAH",
    "GÜLBERAT",
    "UFUK",
    "ZEYNEP",
    "MUSA",
    "NURAN",
    "GÜLAY",
    "SERDAR",
    "CANAN",
    "AHMET",
    "HÜSEYİN",
    "ALPER",
    "CÜNEYT",
    "İLYAS",
    "HALİLİBRAHİM",
    "CANSU",
    "EMEL",
    "SEVAL",
    "EBRU",
    "MUSTAFA KEMAL",
    "MEHMET",
    "AYSU",
    "DUYGU",
    "ASLI",
    "NİHAL",
    "LEYLA",
    "BURÇİN MERYEM",
    "MAHMUT ARDA",
    "SERPİL",
    "AHMET KÜRŞAD",
    "EZGİ",
    "İPEK",
    "HAVVA",
    "ŞAHİN",
    "DENİZ ARMAĞAN",
    "GAMZE",
    "YAŞAR",
    "İLKAY",
    "SAADET NİLAY",
    "HÜSEYİN KALKAN",
    "TAMER",
    "HİDİR",
    "ADEM",
    "AHMET",
    "DERYA",
    "FATİH",
    "YAVUZ SELİM",
    "BEYZA",
    "ÜMİT",
    "AHMET",
    "FETHİ",
    "HİDAYET",
    "MEVLÜT",
    "YAVUZ SELİM",
    "MEHMET FATİH",
    "FETHİYE",
    "MERVE",
    "MEHMET KORAY",
    "EMİNE",
    "MELİKE",
    "MEHTAP",
    "SEVDA",
    "EMİN",
    "EMİR KAAN",
    "MEHMET HİLMİ",
    "HAVVA",
    "LÜTFİ",
    "EMİNE",
    "ELÇİN",
    "MUSTAFA",
    "GÖZDE GİZEM",
    "TEVHİD",
    "AYŞE GÜL",
    "FATMA",
    "TİMUÇİN",
    "BİROL",
    "MUAMMER",
    "DİLŞAH",
    "YAŞAR BARBAROS",
    "ELİF NİHAL",
    "YASEMİN",
    "ŞAHİN",
    "ALİ",
    "EMRAH",
    "AYŞE",
    "YAKUP ONUR",
    "ÇAĞRI",
    "BAHADIR",
    "KURTULUŞ",
    "KADİR",
    "MUSTAFA",
    "YALÇIN",
    "CEREN BUĞLEM",
    "ESRA",
    "ÜMİT",
    "ŞERİFE",
    "ŞEYDA",
    "ASLI",
    "NESLİHAN",
    "ESRA",
    "ÇAĞRI SERDAR",
    "MEHMET ALİ",
    "KAMURAN",
    "DERYA PINAR",
    "MERYEM",
    "ŞİRİN",
    "HARUN",
    "HARUN",
    "PINAR",
    "BARIŞ",
    "FATİH AVNİ",
    "İBRAHİM",
    "DAMLA",
    "MERVE",
    "ÖKKEŞ CELİL",
    "AYŞE",
    "RECEP",
    "EMRE",
    "HALİL",
    "MURAT",
    "SERKAN",
    "ALEV",
    "MÜŞERREF",
    "FATİH",
    "AHMET",
    "ADNAN",
    "HİSAR CAN",
    "ONUR",
    "ALP",
    "MUSTAFA",
    "ÇİĞDEM",
    "SERKAN",
    "ELİF",
    "HASAN",
    "AHMET",
    "BAKİ",
    "SEDA",
    "HANDAN",
    "AYLİN SEVİL",
    "NECMİYE GÜL",
    "ÖZLEM",
    "VOLKAN",
    "SERDAR",
    "EBRU",
    "ERTUNÇ ONUR",
    "EMRE",
    "PINAR",
    "MUHAMMED",
    "SONGÜL",
    "SÜMEYYE",
    "MEVSİM",
    "TUĞBERK",
    "UĞUR",
    "AHMET BURAK",
    "EMRE",
    "YİĞİT CAN",
    "FATİH MEHMET",
    "METE CAN",
    "ESRA",
    "FERHAT",
    "YELİZ",
    "SEVGÜL",
    "CÜNEYT",
    "SEYFULLAH",
    "HALİL CANSUN",
    "FATMA ESRA",
    "SERDAR",
    "YUNUS EMRE",
    "SEZAİ",
    "TAHİR",
    "VEYSİ",
    "YILDIRAY",
    "ELİF",
    "SERHAT",
    "ÖMER",
    "ÖZGE",
    "GÜLSÜM",
    "DENİZ",
    "SELİN",
    "GÜL",
    "BİLGE",
    "ŞEHMUS",
    "DİDEM",
    "MERVE",
    "EYYÜP",
    "NAZLI HİLAL",
    "HATİCE ÖZGE",
    "ABDULLAH",
    "MURAT",
    "HAYATİ CAN",
    "MERVE",
    "FERAY",
    "HASAN",
    "GAMZE",
    "HASAN",
    "RAMAZAN FERHAD",
    "BETÜL",
    "NESLİHAN",
    "MUSTAFA",
    "AYTAÇ",
    "SENA",
    "ZÜHTÜ BENER",
    "EMRE",
    "OSMAN",
    "BULUT",
    "ERSİN",
    "HALİL İBRAHİM",
    "AHMET",
    "SELÇUK",
    "NURMUHAMMET",
    "YASİN",
    "ÖZGE",
    "ZEKİYE SEVAL",
    "ERDEM",
    "DİLEK",
    "ŞULE",
    "GÖKNUR",
    "SALİHA",
    "VELİT",
    "MUHAMMED NURİ",
    "İBRAHİM",
    "TURGAY",
    "ENGİN",
    "HÜSEYİN",
    "MESUT",
    "LEYLA",
    "TUBA",
    "MEHMET ALİ",
    "SALMAN",
    "ŞEYHMUS",
    "ZEHRA",
    "NURDAN",
    "CEBBAR",
    "ÖMER",
    "AHMET",
    "SİNAN",
    "ALPEREN",
    "MEHMET SELAMİ",
    "ABDULAZİZ",
    "LEYLA",
    "FATMA",
    "MÜNEVER",
    "MÜRSELİN",
    "EMRULLAH",
    "EDA",
    "ÜMİT",
    "BÜNYAMİN",
    "RIDVAN",
    "ADEM",
    "ORHAN",
    "EMİNE",
    "KEMAL",
    "FATMA",
    "ALİ",
    "MEHMET",
    "MUSTAFA",
    "NEVZAT",
    "OSMAN",
    "ONUR",
    "MUSTAFA ALİ",
    "MEHTAP",
    "MURAT",
    "MUSA",
    "FİLİZ",
    "HALENUR",
    "KEZİBAN",
    "EFRUZ",
    "EMİN",
    "FATİH",
    "ÜNAL",
    "VOLKAN",
    "BAYRAM",
    "BERAAT",
    "MEHMET",
    "MÜCAHİT",
    "SABRİ SEFA",
    "RAŞAN",
    "RABİA ŞEBNEM",
    "AHMET",
    "AHMET",
    "ZÜBEYDE",
    "BÜŞRA",
    "BURCU",
    "ALİ",
    "IŞIL",
    "GÖZDE",
    "ESMA",
    "KÜBRA",
    "YAŞAR GÖZDE",
    "YILMAZ",
    "ZEYNEP",
    "CANER",
    "VOLKAN",
    "EMRE KAĞAN"
]


var iller=['Adana', 'Adıyaman', 'Afyon', 'Ağrı', 'Amasya', 'Ankara', 'Antalya', 'Artvin',
'Aydın', 'Balıkesir', 'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale',
'Çankırı', 'Çorum', 'Denizli', 'Diyarbakır', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir',
'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Isparta', 'Mersin', 'İstanbul', 'İzmir', 
'Kars', 'Kastamonu', 'Kayseri', 'Kırklareli', 'Kırşehir', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya', 
'Manisa', 'Kahramanmaraş', 'Mardin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Rize', 'Sakarya',
'Samsun', 'Siirt', 'Sinop', 'Sivas', 'Tekirdağ', 'Tokat', 'Trabzon', 'Tunceli', 'Şanlıurfa', 'Uşak',
'Van', 'Yozgat', 'Zonguldak', 'Aksaray', 'Bayburt', 'Karaman', 'Kırıkkale', 'Batman', 'Şırnak',
'Bartın', 'Ardahan', 'Iğdır', 'Yalova', 'Karabük', 'Kilis', 'Osmaniye', 'Düzce']


const brokoli=[ 
"Company Logo", 
"e-Fatura", 
"ULUGÖK ORGANİK TARIM ÜRÜNLERİ PAZ.GIDA VE",
"NAK.TİC.",
"KOCATEPE HALYOLU MERKEZ HAL NO:151 MERKEZ",
"No:151", 
"BAYRAMPAŞA / İSTANBUL", 
"Web Sitesi: www",
"E-Posta: ulugok151@hotmail.com",
"Vergi Dairesi: TUNA",
"VKN: 8890370481",
"TICARETSICILNO: 801862",
"Fatura No: EMF2023000000739",
"Özelleştirme No:TR1.2",
"Senaryo:HKS",
"Fatura Tipi:KOMISYONCU",
"Stok Giriş Tarihi:24.10.2023",
"Marka:XX",
"Düzenleme Tarihi:16.11.2023",
"Düzenleme Zamanı:09:05:00.0000000+03:00",
"SAYIN",
"EMRE YAVUZ",
"SAMSUN MERKEZ KÖYLER TEKKEKÖY/SAMSUN",
"Tel: 533",
"Vergi Dairesi: TC",
"VKN: 3341183468",
"ETTN: 26865443-62E1-4C9B-97DD-7EF09F1481DD",
"Mal Hizmet Toplam Tutarı1.622,00 TL",
"Gerçek usülde katma değer",
"vergisi %1.00 (Matrah: 1.622,00)",
"16,22 TL",
"Vergiler Dahil Toplam Tutar1.638,22 TL",
"Toplam Masraflar272,08 TL",
"Fatura Tutarı1.366,14 TL",
"Net Yekün1.366,14 TL",
"Masraflar",
"Komisyon - %129,76 TL%8,00",
"Komisyon KDV - %25,95 TL%20,00",
"Navlun - %69,94 TL",
"Navlun KDV - %13,99 TL%20,00",
"Diğer Masraflar - %32,44 TL",
"BANKA HESAP BİLGİLERİMİZ",
"Banka AdıIBAN",
"HALK BANKTR69 0001 2001 2200 0010 1010 30 TL hesabı",
"BinÜçYuzAltmışAltıTLOnDörtKR",
"İrsaliye yerine geçer.",
"Sıra",
"No",
"Ürün",
"Kodu",
"Ürün AdıKünyeKapDaralıDaraMiktarBirimBirim Fiyat",
"KDV",
"Oranı",
"KDV Tutarı",
"Mal Hizmet",
"Tutarı",
"1BRBROKOLİ1353269230020986414559,00,059.0KG10,000 TL1,005,90 TL590,00 TL",
"2BRBROKOLİ1353269230020986414678,00,078.0KG7,000 TL1,005,46 TL546,00 TL",
"3BRBROKOLİ13532692300209864149108,00,0108.0KG4,500 TL1,004,86 TL486,00 TL",
"Toplam :20245,00,0245,0"
]
const nonEmptyTextLines2 = [
    'EMRE YAVUZ GIDA ÜRÜNLERİ SANAYİ VE TİCARET',
    'LİMİTED ŞİRKETİ',
    'KABABÜRÜK MAH. KABABÜRÜK KÜMESİ KÜME EVLER NO:',
    '276',
    '55300 TEKKEKÖY/SAMSUN',
    'Vergi Dairesi: 19 MAYIS  VKN:3341183468',
    'IFCO Lojistik Sistemleri Ticaret Limited Şirketi.',
    'Barbaros Mh. Begonya Sokak No:3 D:122 34746',
    'ATAŞEHİR/İSTANBUL',
    'Tel: 0(216) 688 8196',
    'Tel: (216) 688 8197',
    'info@ifco.com',
    'Vergi Dairesi: KOZYATAĞI  VKN:4650110611',
    'SAYIN',
    'Özelleştirme No:TR1.2',
    'Senaryo:TEMELFATURA',
    'Fatura Tipi:IADE',
    'Fatura No:SEY2023000000910',
    'Fatura Tarihi:29-09-2023',
    'İşlem Saati:15:12:45',
    'Ödeme Türü:Vadeli',
    'e-FATURA',
    'ETTN:B8366258-2ACF-4375-A144-4E27E4454793',
    'CinsiAçıklamaMiktarBirimFiyatKdvMal Tutarı',
    'AHŞAP PALET SATIŞ BEDELİ 72  Ad125,00  %20 9.000,00',
    'CHEP PALET 1208 34  Ad0,00  %20 0,00',
    'Fatura Dahil Bakiye',
    '-766.805,18 Alacak',
    'Yalnız onbinsekizyüz TL',
    'Mal Toplamı 9.000,00 TL',
    'Hesaplanan KDV(%20) 1.800,00 TL',
    'Masraf Toplamı',
    'Vergiler Dahil Toplam Tutar 10.800,00 TL',
    'Ödenecek Tutar 10.800,00 TL',
    'T.GARANTİ BANKASI A.Ş.BUĞDAYPAZARI ŞB.TR720006200144600006296613',
    'Tarih:29-09-2023 Saat:15:12:45 İrsaliye yerine geçer.'
  ]
  const nonEmptyTextLines3 = [
    'SAYIN',
    'EMRE YAVUZ GIDA ÜRÜNLERİ (Marka:X)',
    'MERKEZ/ İSTANBUL',
    'Tel: Fax:',
    'Vergi Dairesi: 19 MAYIS',
    'VKN: 3341183468',
    'Özelleştirme',
    'No:',
    'TR1.2',
    'Senaryo:HKS',
    'Fatura Tipi:KOMISYONCU',
    'Fatura No:VMH2023000001797',
    'Fatura Tarihi:04-11-2023',
    'Fatura Saati:09:24:08.0000000+03:00',
    'Stok Giriş',
    'Tarihi:',
    '24-10-2023',
    'Malzeme/Hizmet AçıklamasıKünyeKapMiktarBirim Fiyat',
    'KDV',
    '%',
    'KDV TutarıMal Hizmet Tutarı',
    'PIRASA   2 22.00 18.00 TL  %1  3.96 TL 396.00 TL',
    'PIRASA   1 12.00 13.00 TL  %1  1.56 TL 156.00 TL',
    'PIRASA   17 210.38 1.00 TL  %1  2.10 TL 210.38 TL',
    'Toplam:20244.38',
    'Yalnız: Altı Yüz İki Türk Lirası Yirmi Bir Kuruş',
    'Harici Masraf:38,12',
    'VİZYON EKOLOJİK TARIM ÜRÜNLERİ SANAYİ VE TİCARET',
    'LİMİTED ŞİRKETİ',
    'KOCATEPE MAH HAL YOLU SOK HAL NO :85/1  No:',
    '34200 KOCATEPE/ İSTANBUL',
    'Tel: 5325588290 Fax: 5325588290',
    'E-Posta: [HAL.EMAIL]',
    'Vergi Dairesi: TUNA',
    'VKN: 9251061691',
    'MERSISNO: 000000',
    'TICARETSICILNO: 377014-S',
    'e-Fatura',
    'ETTN: C3C0ABC8-BEBD-4CAB-9213-5DE220B30452',
    'Komisyon (%5.00)38.12 TL',
    'Komisyon KDV7.62 TL',
    'Navlun69.94 TL',
    'Navlun KDV13.99 TL',
    'Diğer Masraflar38.12 TL',
    'Diğer KDV0.00 TL',
    'Mal Hizmet Toplam Tutarı762.38 TL',
    'Toplam İskonto0.00 TL',
    'Hesaplanan KDV(%1.00)7.62 TL',
    'Vergiler Dahil Toplam Tutar770.00 TL',
    'Vergiler167.79 TL',
    'Ödenecek Tutar602.21 TL'
  ]
  const gsm=[
"FATURA ID",
"Fatura Tarihi",
"Fatura Dönemi", 
":",
":",
":",
"0012023190409911",
"25/10/2023",
"28/09/2023-24/10/2023",
"e-Fatura",
"TELEFON NO:5308515597",
"ETTN",
"Müşteri No",
"Vergi Dairesi / No",
":",
":",
":",
"dc1ee360-9942-4156-a231-4f4942eef90e",
"7.3559672.00.00.100001",
"19 Mayis Vergi Daire/3341183468 5308515597", 
"EMRE YAVUZ GIDA ÜRÜNLERİ",
"SANAYİ VE TİCARET LİMİTED",
"ŞİRKETİ",
"Karşıyaka Mh. Milli Mücadele Sk.",
"No:35 D:8",
"Canik 55080 Samsun",
"ÖDENECEK TUTAR:417.40 TRY",
"TOPLU ÖDEME NO:9003364103",
"SON ÖDEME TARİHi:06/11/2023",
"Faturanızın üzerinde yazan toplu",
"ödeme numarası ile firmanıza ait",
"tüm faturalarınızı tek seferde",
"ödeyebilirsiniz.",
"Tarife ve Paket Ücretleri275.41",
"KULLANIMLARINIZLA İLGİLİ ÜCRETLER",
"İndirimler-316.57",
"Düzeltmeler-0.01",
"Tahsilatına Aracılık Edilen Ödemeleriniz40.52",
"FATURANIZDAKİ DİĞER KALEMLER",
"FATURA TUTARI",
"417.40 TRY",
"Yalnız - DÖRTYÜZONYEDİTLKIRKKR",
"Katma Deger Vergisi%20(Matrah:275.41 TRY)55.08",
"Özel İletişim Vergisi%10(Matrah:275.41 TRY)27.54",
"Telsiz Ruhsat Yeni Abonelik Taksiti%0(Matrah:56.57 TRY)56.57",
"Telsiz Kullanım Aylık Taksit%0(Matrah:18.86 TRY)18.86",
"Yeni Tesis Özel İletişim Vergisi%0(Matrah:260.00 TRY)260.00"
]


const pdfTry1=[
"EMRE YAVUZ GIDA ÜRÜNLERİ SANAYİ VE TİCARET",
"LİMİTED ŞİRKETİ", 
"KABABÜRÜK MAH. KABABÜRÜK KÜMESİ KÜME EVLER NO:", 
"276", 
"55300 TEKKEKÖY/SAMSUN", 
"Vergi Dairesi: 19 MAYIS  VKN:3341183468",
"BİM BİRLEŞİK MAĞAZALAR A.Ş.",
"CİHADİYE MAHALLESİ 23081 SOKAK NO: 9",
"AKSU/ANTALYA",
"AKSU/ANTALYA",
"Vergi Dairesi: BÜYÜK MÜK. VD. B  VKN:1750051846",
"SAYIN",
"Özelleştirme No:TR1.2",
"Senaryo:HKS",
"Fatura Tipi:SATIS",
"Fatura No:SEY2023000000912",
"Fatura Tarihi:03-10-2023",
"İşlem Saati:13:36:52",
"İrsaliye No:IEY2023000000372",
"İrsaliye Tarihi:01-10-2023",
"e-FATURA",
"ETTN:43431485-76F0-4B92-8737-3842C01FF65B",
"CinsiAçıklamaKünyeKs/AdBğ/KgFiyatKdvTutar",
"DOMATES SALÇALIK  1423369230020992884710 Ad12.040 Kg8,00  %1 96.320,00",
"Kasa",
"Bağ",
"Adet 710",
"Safi 12.040",
"Plaka 01AIH918",
"Hamaliye",
"Hamaliye KDV",
"Nakliye",
"Nakliye KDV",
"İ.Sandık",
"İ.Sandık KDV",
"Mal Toplamı 96.320,00 TL",
"Hesaplanan KDV(%1) 963,20 TL",
"Masraf Toplamı 0,00 TL",
"Vergiler Dahil Toplam Tutar 97.283,20 TL",
"Ödenecek Tutar 97.283,20 TL",
"Yalnız doksanyedibinikiyüzseksenüç TL yirmi Kr",
"9490 FİLE ANTALYA DEPOYA SEVK EDİLMİŞTİR.17 TURPAL PALET/6416-710 KASA",
"T.GARANTİ BANKASI A.Ş.BUĞDAYPAZARI ŞB.TR720006200144600006296613",
"Tarih:01-10-2023 Saat:13:36:52 İrsaliye yerine geçer."
]

const pdfTry2=[
"EMRE YAVUZ GIDA ÜRÜNLERİ SANAYİ VE TİCARET",
"LİMİTED ŞİRKETİ",
"KABABÜRÜK MAH. KABABÜRÜK KÜMESİ KÜME EVLER NO:",
"276",
"55300 TEKKEKÖY/SAMSUN",
"Vergi Dairesi: 19 MAYIS  VKN:3341183468",
"BİM BİRLEŞİK MAĞAZALAR A.Ş.",
"FİLE - ORHANGAZİ MAH. ATATÜRK BULVARI NO: 59",
"ESENYURT / İSTANBUL",
"ESENYURT/İSTANBUL",
"Vergi Dairesi: BÜYÜK MÜK. VD. B  VKN:1750051846",
"SAYIN",
"Özelleştirme No:TR1.2",
"Senaryo:HKS",
"Fatura Tipi:SATIS",
"Fatura No:SEY2023000000947",
"Fatura Tarihi:06-12-2023",
"İşlem Saati:10:23:25",
"İrsaliye No:IEY2023000000410",
"İrsaliye Tarihi:06-12-2023",
"e-FATURA",
"ETTN:304DB106-B0F0-4EB5-8188-77C0AA4250EE",
"CinsiAçıklamaKünyeKs/AdBğ/KgFiyatKdvTutar",
"BEYAZ LAHANA  15531792300263201861 Ad330 Kg6,00  %1 1.980,00",
"Kasa",
"Bağ",
"Adet 1",
"Safi 330",
"Plaka 61K6110",
"Hamaliye",
"Hamaliye KDV",
"Nakliye",
"Nakliye KDV",
"İ.Sandık",
"İ.Sandık KDV",
"Mal Toplamı 1.980,00 TL",
"Hesaplanan KDV(%1) 19,80 TL",
"Masraf Toplamı 0,00 TL",
"Vergiler Dahil Toplam Tutar 1.999,80 TL",
"Ödenecek Tutar 1.999,80 TL",
"Yalnız bindokuzyüzdoksandokuz TL seksen Kr",
"FİLE ESENYURT DEPO",
"T.GARANTİ BANKASI A.Ş.BUĞDAYPAZARI ŞB.TR720006200144600006296613",
"Tarih:06-12-2023 Saat:10:23:25 İrsaliye yerine geçer.",
]
const nonEmptyTextLine = [
    'Özelleştirme No:TR1.2',
    'Senaryo:TEMELFATURA',
    'Fatura No:IF22023000000961',
    'Fatura Tipi:SATIS',
    'Fatura Tarihi24.10.2023',
    'Fatura No10050912',
    'Müşteri No649372',
    'İrsaliye No:/ PS02023000000189/ PS02023000000190',
    'Ödeme koşulları: 30 gün icinde Indirimsiz',
    'Yalnız : ONSEKIZBINOTUZALTI TL ONDÖRT KRŞ',
    'IFCO LOJİSTİK SİSTEMLERİ TİC. LTD. ŞTİ.',
    'HSBC BANK / KÜRESEL BANKACILIK MERKEZİ ŞB.',
    'TL IBAN:TR64 0012 3001 2310 0031 2282 00',
    'IFCO Lojistik Sistemleri Ticaret Limited Şirketi.',
    'Barbaros Mh. Begonya Sokak NIDAKULE KUZEY No:3',
    'D:122 34746 Ataşehir / İstanbul Türkiye',
    'Tel: 0216 688 81 96 Faks: 0216 688 81 97',
    'E-Posta: info@ifco.com',
    'Vergi Dairesi: KOZYATAĞI VERGİ DAİRESİ',
    'Vergi Numarası: 4650110611',
    'Web Sitesi: www.ifcosystems.com.tr',
    'Sicil No:444282',
    'Mersis No:0465011061100016',
    'İşletme Merkezi:BATI ATASEHIR ISTANBUL',
    'SAYIN',
    'EMRE YAVUZ GIDA URUNLERI SAN. VE TIC. LTD. STI.',
    'Karaburuk Mah. Karaburuk Kumesi Kume Evler No: 276 NO: No:',
    '276',
    'Tekkekoy / Samsun',
    'Vergi Dairesi: 19 MAYIS',
    'Vergi Numarası: 3341183468',
    'e-FATURA',
    'qrcode',
    'ETTN: 0050568E-569B-1EEE-9CFF-5526C3C9EBC7',
    'Sıra',
    'No',
    'Ürün KoduAçıklamaMiktarBirim FiyatNet Tutar',
    '1 CH3415 Kasa teslim (kiralama) bedeli CH3415 544  Adet 6,66 3.623,04  TL',
    '2 CH6416 Kasa teslim (kiralama) bedeli CH6416 1.088  Adet 9,91 10.782,08  TL',
    '3 EP Ahşap palet satış bedeli 5  Adet 125,00 625,00  TL',
    'Toplam :15.030,12 TL',
    'Hesaplanan KDV %20,00 :3.006,02 TL',
    'Genel Toplam :18.036,14 TL'
  ]

  const pdfTry3=[
"SAYIN",
"EMRE YAVUZ GIDA ÜRÜNLERİ SANAYİ VE TİCARET LİMİTED",
"ŞİRKETİ",
"No:",
"Kapı No:",
"/",
"tr",
"Web Sitesi:", 
"E-Posta:",
"Tel:",
"Vergi Dairesi: 19 MAYIS MAL MÜDÜRLÜGÜ",
"VKN: 3341183468",
"ÖZKAN TARIM",
"TUNAY  ÖZKAN",
"GAZIPASA MAH OGUZHAN CAD NO: 94   No:",
"Kapı No:",
"BAFRA/ SAMSUN",
"Tel: 05439348513 Fax:",
"Web Sitesi: tunayozkan55@gmail.com",
"E-Posta: tunayozkan55@gmail.com",
"Vergi Dairesi: BAFRA VERGI DAIRESI",
"TCKN: 34211170290",
"Mersis No:",
"Ticaret Sicil No:",
"e-FATURA",
"Özelleştirme No:TR1.2",
"Senaryo:TICARIFATURA",
"Fatura Tipi:SATIS",
"Fatura No:TOF2023000000526",
"Fatura Tarihi:04-12-2023 10:55",
"ETTN:   12890199-45fc-4850-a326-43082355666e",
"Sıra",
"No",
"Mal HizmetMiktarBirim Fiyat",
"İskonto/",
"Arttırım",
"Oranı",
"İskonto/",
"Arttırım",
"Tutarı",
"KDV",
"Oranı",
"KDV TutarıDiğer Vergiler",
"Mal Hizmet",
"Tutarı",
"1 KIRMIZI LAHANA 1.030 kg 5,9406 TL",
"(+)",
"%0,00",
"0,00 TL  %1,00  61,19 TL",
"6.118,81 TL",
"2 HİBRİT LAHANA 23.100 kg 2,4752 TL",
"(+)",
"%0,00",
"0,00 TL  %1,00  571,78 TL",
"57.178,23 TL",
"Mal Hizmet Toplam Tutarı63.297,04 TL",
"Toplam İskonto0,00 TL",
"Hesaplanan KDV(%1.00)632,97 TL", 
"Vergiler Dahil Toplam Tutar63.930,01 TL",
"Ödenecek Tutar63.930,01 TL",
"Not: YALNIZ : ALTMIŞÜÇBİNDOKUZYÜZOTUZ TL BİR KURUS", 
"Not:"
]

const pdfTry4=[
  "SAYIN",
  "EMRE YAVUZ GIDA ÜRÜNLERİ SANAYİ VE TİCARET LİMİTED",
  "ŞİRKETİ",
  "KABABÜRÜK MAH. KABABÜRÜK KÜMESİ KÜME EVLER 276",
  "Tekkeköy/ Samsun",
  "E-Posta:",
  "Tel:",
  "Vergi Dairesi: 19 MAYIS VERGİ DAİRESİ MÜD.",
  "VKN: 3341183468",
  "SUBENO:",
  "MUSTERINO:",
  "Özelleştirme No:TR1.2",
  "Senaryo:TICARIFATURA",
  "Fatura Tipi:TEVKIFAT",
  "Fatura No:EEE2023000000217",
  "Fatura Tarihi:06-12-2023 13:57",
  "Tevkifat Sebebi: 624---> (2/10) YÜK TAŞIMACILIĞI HİZMETİ [KDVGUT-(I/C-2.1.3.2.11)]+",
  "Not: Yazı ile: # Yirmi Üç Bin İki Yüz TL #",
  "BANKA HESAP BİLGİLERİ",
  "BANKAHESAP TÜRÜIBAN",
  "GARANTİ BANKASITLTR 12 0006 2000 6530 0006 2984 57",
  "GARANTİ BANKASIUSDTR 73 0006 2000 6530 0009 0906 68",
  "GARANTİ BANKASIEUROTR 92 0006 2000 1580 0009 0906 67",
  "EMLAK KATILIMTLTR 21 0021 1000 0006 9110 9000 01",
  "EMLAK KATILIMUSDTR 37 0021 1000 0006 9110 9001 01",
  "TÜRKİYE İŞ BANKASITLTR 19 0006 4000 0017 5200 3056 58",
  "TÜRKİYE İŞ BANKASIUSDTR 85 0006 4000 0027 5200 2311 33",
  "Bu fatura Uysal Yazılım E-Belge Tasarım Aracı kullanılarak tasarlanmıştır.",
  "DERYA ULUSLARARASI TAŞ.GÜM.İNŞ.İÇ VEDIŞ TİC.LTD.ŞTİ.",
  "NEFSİPULATHANE MAHALLESİ ATATÜRK BULVARI SEBAT",
  "İŞHANI NO:49/215",
  "Akçaabat/ Trabzon",
  "Tel: 8508236336",
  "E-Posta: meryemturkmen",
  "Vergi Dairesi: AKÇAABAT VERGİ DAİRESİ MÜD.",
  "VKN: 2930079648",
  "SUBENO:",
  "MERSISNO:",
  "HIZMETNO:",
  "TICARETSICILNO:",
  "e-FATURA",
  "ETTN: d869965c-1e31-4744-a23c-214c0492e643",
  "Sıra",
  "No",
  "Mal HizmetMiktarBirim Fiyat",
  "İskonto",
  "Oranı",
  "İskonto",
  "Tutarı",
  "KDV OranıKDV TutarıDiğer Vergiler",
  "Mal Hizmet",
  "Tutarı",
  "1",
  "61K8448-61AFP767 BAFRA",
  "İSTANBUL NAKLİYE BEDELİ",
  "1 Adet 20.000 TL    %20,00  4.000,00 TL",
  "KDV TEVKİFAT",
  "(%20,00)=800,00 TL",
  "20.000,00 TL",
  "Mal Hizmet Toplam Tutarı20.000,00 TL",
  "Toplam İskonto0,00 TL",
  "Hesaplanan KDV GERCEK(%20)",
  "(20.000,00)",
  "4.000,00 TL",
  "Hesaplanan KDV Tevkifat(%20)800,00 TL",
  "Tevkifata Tabi İşlem Tutarı20.000,00TL",
  "Tevkifata Tabi İşlem Üzerinden Hes. KDV4.000,00TL",
  "Vergiler Dahil Toplam Tutar24.000,00 TL",
  "Ödenecek Tutar23.200,00 TL"
]

const pdfTry5=[
"Özelleştirme No:TR1.2",
"Senaryo:TEMELFATURA",
"Fatura No:BD42023000044589",
"Fatura Tipi:IADE",
"Sipariş No:5118969772",
"Sipariş Tarihi:30-10-2023",
"Referans No:5163467815",
"Fatura Tarihi:31.10.2023",
"YALNIZ : ONBEŞBİNÜÇYÜZALTMIŞİKİ TL VE ON KR",
"Kod, İrsaliye Numaraları ve Tarihleri :",
"9403 - BE02023003810232 - 30.10.2023",
"Merkez Adresi :",
"BİM Birleşik Mağazalar A.Ş.",
"Abdurrahmangazi Mah. Ebubekir Cad.   No: 73  Sancaktepe / Istanbul",
"E-Posta: earsiv@bim.com.tr",
"Vergi Dairesi: BÜYÜK MÜKELLEFLER",
"Vergi Numarası: 1750051846",
"Web Sitesi: www.bim.com.tr",
"Mersis No:0175005184608645",
"İşletme Merkezi:Sancaktepe",
"FİLE Bölge(9401)",
"Hamidiye Mah. Mimar Sinan Cad.",
"Çekmeköy / İSTANBUL",
"Tel: 0216 2173535",
"e-Fatura",
"qrcode",
"EMRE YAVUZ GIDA ÜRÜNLERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ",
"KABABÜRÜK MAH KÜME EVLER NO:76 TEKKEKÖY/SAMSUN",
"Samsun",
"Vergi Dairesi: 19 MAYIS",
"Vergi Numarası: 3341183468",
"E-Posta: e.yavuz.1@hotmail.com",
"ETTN: 0050569F-E0FF-1EDE-9F8D-E77D0D49EC4C",
"Malzeme",
"Kodu/Code",
"Açıklama/DescriptionMiktar/QuantityFiyat/PriceTutarı/Amount",
"41100084    PIRASA KG 845  KG 18 TL15.210 TL",
"Toplam Tutar:15.210,00TL",
"Hesaplanan KDV (15.210,00) %1.00:152,10TL",
"Fatura Tutarı:15.362,10TL"
]
  const allPossible=[
    'özelleştirme', 
    'sayin', 
    "vkn",
    'senaryo',
    'TEMELFATURA',
    'Fatura',
    'tipi',
    'iade',
    'geçici',
    'proforma',
    'irsaliye',
    'tarihi',
    'müşteri', 
    'odeme',
    'gün', 
    'ındirimsiz',
    'yalnız',
    'merkezi',
    'mh.',
    'sok.',
    'sokak',
    'türkiye',
    'e-posta',
    '@',
    'vergi', 
    'daire',
    'numara',
    'web',
    'sitesi',
    'www.',
    '.com',
    '.tr',
    'sicil',
    'mersis',
    'işletme',
    'merkez',
    'sayın',
    'san.',
    'tic',
    'tıc',
    'ltd',
    'sti',
    'e-FATURA',
    'qrcode',
    'ETTN',
    'toplam',
    'hesaplanan',
    'genel',
    'özelleştirme',
    'işlem',
    'ödeme Türü',
    'vadeli',
    'bakiye',
    'alacak',
    'masraf',
    'fax',
    'giriş',
    'komisyon',
    'navlun',
    "IBAN",
    "ticaret",
    "limited",
    "LİMİTED",
    "TİCARET",
    "MAH",
    "YOLU",
    "SOK",
    "TR1.2",
    "şirketi",
    "sirketi",
    "KDV",
    "hesabı",
    "NAK.",
    "Logo",
    "PAZ.",
    "Company",
    "Düzenleme",
    "Zamanı",
    "Kodu",
    "Gerçek",
    "usülde",
    "Yekün",
    "Mersis No:",
    "GARANTİ",
    "EMLAK KATILIM",
    "TÜRKİYE İŞ BANKASI",
    "#",
    "tevkifat"

    ]
    const bankalar=[
      "adabank",
      "akbank",
      "alternatifbank",
      "anadolubank",
      "arap türk bankası",
      "ban of china turkey",
      "burgan bank",
      "citibank",
      "denizbank",
      "deutsche bank",
      "fibabanka",
      "habib bank limited istanbul türkiye merkez şubesi",
      "hsbc bank",
      "icbc turkey bank",
      "ing bank",
      "intesa sanpaolo s.p.a.",
      "jp morgan chase bank national association",
      "mufg bank turkey",
      "odea bank",
      "qnb finansbank",
      "rabobank",
      "societe generale",
      "şekerbank",
      "t.c. ziraat bankası",
      "turkish bank",
      "turkland bank",
      "türk ekonomi bankası",
      "türk ticaret bankası",
      "türkiye garanti bankası",
      "türkiye halk bankası",
      "türkiye iş bankası",
      "türkiye vakıflar bankası",
      "yapı ve kredi bankası",
      "YAPIKREDİ",
      "HALKBANK",
      "TEB",
      "ZİRAAT",
      "ODEABANK",
      "HSBC",
      "ING BANK",
      "ŞEKERBANK"
    ]
  const allPossibleSecondLayer=[
    'özelleştirme', 
    'sayin', 
    "vkn",
    'senaryo',
    'TEMELFATURA',
    'Fatura',
    'tipi',
    'iade',
    'geçici',
    'proforma',
    'irsaliye',
    'tarihi',
    'müşteri', 
    'odeme',
    'gün', 
    'ındirimsiz',
    'yalnız',
    'merkezi',
    'mh.',
    'sok.',
    'sokak',
    'türkiye',
    'e-posta',
    '@',
    'vergi', 
    'daire',
    'numara',
    'web',
    'sitesi',
    'www.',
    '.com',
    '.tr',
    'sicil',
    'mersis',
    'işletme',
    'merkez',
    'sayın',
    'san.',
    'tic',
    'tıc',
    'ltd',
    'sti',
    'e-FATURA',
    'qrcode',
    'ETTN',
    'toplam',
    'hesaplanan',
    'genel',
    'özelleştirme',
    'işlem',
    'ödeme Türü',
    'vadeli',
    'bakiye',
    'alacak',
    'masraf',
    'fax',
    'giriş',
    'komisyon',
    'navlun',
    "IBAN",
    "ticaret",
    "limited",
    "LİMİTED",
    "TİCARET",
    "MAH",
    "YOLU",
    "SOK",
    "TR1.2",
    "şirketi",
    "sirketi",
    "KDV",
    "%",
    "No:",
    "No",
    "NO",
    "Ürünler",
    "Malzeme",
    "Açıklama",
    "Künye",
    "Fiyat",
    "TL",
    "Ödenecek",
    "Tutar",
    "İrsaliye",
    "Tel:",
    "Faks:",
    "Sıra",
    "Ürün",
    "teslim",
    "bedeli",
    "Adet",
    "adet",
    "İşlem",
    "saati:",
    "Saat:",
    "Tarih:",
    "yerine",
    "geçer",
    "hesabı",
    "Mal",
    "Hizmet",
    ":",
    "YALNIZ",
    "BİR",
    "İskonto",
    "Not:",

    ]
    
    const avoidnumberWords = [
      'bir',
      'iki',
      'üç',
      'dört',
      'beş',
      'altı',
      'yedi',
      'sekiz',
      'dokuz',
      'on',
      'yirmi',
      'otuz',
      'kırk',
      'elli',
      'altmış',
      'yetmiş',
      'seksen',
      'doksan',
      'yuz',
      'bin',
      'Bir',
      'İki',
      'Üç',
      'Dört',
      'Beş',
      'Altı',
      'Yedi',
      'Sekiz',
      'Dokuz',
      'On',
      'Yirmi',
      'Otuz',
      'Kırk',
      'Elli',
      'Altmış',
      'Yetmiş',
      'Seksen',
      'Doksan',
      'Yuz',
      'Bin',
      "BİR",
      "İKİ",
      "DÖRT",
      "BEŞ",
      "ALTI",
      "YEDİ",
      "SEKİZ",
      "DOKUZ",
      "ON",
      "YİRMİ",
      "OTUZ",
      "KIRK",
      "ELLİ",
      "ALTMIŞ",
      "ATMIŞ",
      "YETMİŞ",
      "SEKSEN",
      "DOKSAN",
      "YÜZ",
      "BİN"
    ];
    const avoidtableHeader = [
      'Adı',
      'Künye',
      'Kap',
      'Daralı',
      'Dara',
      'Miktar',
      'Birim',
    ];
  


const possibleForUnit = ["Adet", "KG","Kg", "adet","Ad", "kg", "ad"];


function isAlpha(char) {
  // Check if the character is an alphabet character
  return /^[a-z]$/i.test(char);
}
function containsConsecutiveAvoidWords(arr,line) {

  var result;
  let consecutiveCount = 0;

  for (const word of arr) {
    if (String(line).includes(word)) {
      consecutiveCount++;
      if (consecutiveCount >= 2) {
        result= true;
      }
    } else {
      consecutiveCount = 0;
      result=false
    }
  }

  return result;
}
function extractInfo(line) {
  // result object başlat
  const result = {};
//fatura tipini tedspit et
  var priceType;
  var splitted=String(line).split(" ");
  var trimmedAndFiltered = splitted.map(element => element.trim()).filter(Boolean);
  var TLcount=trimmedAndFiltered.filter(f=>f==="TL").length;
  if(TLcount===3){
    priceType="uclu"
  }
  const tlIndices = [];
  trimmedAndFiltered.forEach((word, index) => {
  if (word === 'TL') {
    tlIndices.push(index);
  }
});

  var billType;
  if(String(line).includes("%")){
    billType="kdvli";
    const kdvMatch = line.match(/%(\d+)/);
    result.KDV = kdvMatch ? `%${kdvMatch[1]}` : null;
    if(!possibleForUnit.some(s=>String(line).includes(s))){
      billType="birimsiz"
    }
  }else if(!String(line).includes("%")){
    billType="kdvsiz"
  }

  // id varsa çıkarma
  const idMatch = line.match(/^\d+/);
  result.id = idMatch ? parseInt(idMatch[0]) : null;

  // birim çıkarma



    // birim fiyat ve adet çıkarma

  if(billType==="kdvsiz"){
    console.log("birim fiyat ve adet çıkarma fonksiyonu")
    var splitted=String(line).split(" ");
    var trimmedAndFiltered = splitted.map(element => element.trim()).filter(Boolean);

    var unitindex=trimmedAndFiltered.reverse().findIndex(f=>possibleForUnit.some(s=>s===f))
    console.log(trimmedAndFiltered)
    result.amount=trimmedAndFiltered[unitindex+1] 
    result.unitPrice=trimmedAndFiltered[unitindex-1]
    result.unit = possibleForUnit.find(unit => line.includes(unit)) || null;


}

if(billType==="kdvli"){
    const amountUnitPriceMatch = line.match(/([\d.,]+)\s*([A-Za-z]+)(?:\s*([\d.,]+)\s*%)?/);
    if (amountUnitPriceMatch) {
      result.amount = parseFloat(amountUnitPriceMatch[1]);
      result.unit = possibleForUnit.find(unit => amountUnitPriceMatch[2].toLowerCase().includes(unit.toLowerCase())) || null;
      result.unitPrice = amountUnitPriceMatch[3] ? amountUnitPriceMatch[3] : null;
    }
}

// Extracting productTotalPrice
  const totalPriceMatch = line.match(/([.,\d]+)$/);
  result.productTotalPrice = totalPriceMatch ? totalPriceMatch[1].replace("TL","") : null;

  if(billType!=="birimsiz"&&billType!=="kdvsiz"){
    result.unit = possibleForUnit.find(unit => line.includes(unit)) || null;
    const unitPriceMatch = line.match(/(\d+[.,]?\d*)\s*%/);
    result.unitPrice = unitPriceMatch ? unitPriceMatch[1] : null;
  
  }
  
  if(billType ==="kdvsiz"){
    var splitted=String(line).split(" ");
    var trimmedAndFiltered = splitted.map(element => element.trim())?.filter(Boolean);
    var unit=trimmedAndFiltered.findIndex(f=>possibleForUnit.some(s=>s===f))
    result.productTotalPrice=trimmedAndFiltered[trimmedAndFiltered.length-2]?.replace("TL","")
  }
  if(billType ==="birimsiz"){
      var splitted=String(line).split(" ");
      var trimmedAndFiltered = splitted.map(element => element.trim()).filter(Boolean);



      const priceRegex = /(\d+\.\d{2})\s*TL$/;
      const match = line.match(priceRegex);
      result.productTotalPrice = match ? match[1] : null;
      result.unit=null;
      
  }
  if(priceType==="uclu"&&(!result.amount||!result.unitPrice)){
    result.unitPrice=trimmedAndFiltered[tlIndices[0]-1];
    result.amount=trimmedAndFiltered[tlIndices[0]-2];
    result.KAP=trimmedAndFiltered[tlIndices[0]-3];
    result.KDVTutar=trimmedAndFiltered[tlIndices[1]-1];

  }


  if(!result.amount && result.unit && line.includes("TL")){
    console.log("bunda amount yoktu ve uunit ten yola çıkıldı")
      var stringedLayer=line.split("").join("").replace(/\s/g,"").trim()
      var splittedLayer = stringedLayer.split(/KG|TL/).filter(Boolean);
    console.log(stringedLayer)
    splittedLayer[0] = splittedLayer[0].split(',')[1];
    console.log(splittedLayer)
    result.unitPrice=splittedLayer[splittedLayer.length-3];
    result.amount=Math.round(parseInt(result.productTotalPrice)/parseInt(result.unitPrice))

  }
  let threshold = Number.MAX_SAFE_INTEGER;

if (Math.abs(result.amount) > threshold && result.unitPrice) {
  result.amount=Math.round(parseInt(result.productTotalPrice.replace(".",""))/parseInt(result.unitPrice.replace(".","")))

} else {
    console.log("This number is within the safe range.");
}
if(result.amount&&result.productTotalPrice&&result.unitPrice&&(result.unitPrice===result.productTotalPrice)){
  result.productTotalPrice=(parseFloat(String(result.unitPrice).replace(",","."))*parseFloat(String(result.amount).replace(".",""))).toFixed(2)

}
  let words = line.match(/[^\d\s]{4,}/g);
  words = words?.filter(word => word !== null);

  // Extracting productName
  const productNameMatch = line
  .replace(/^\d+/, '')  // Remove id
  .replace(result["amount"], '')  // Remove amount and unit
  .replace(result["unit"], '')  // Remove amount and unit
  .replace(result["unitPrice"],'') //remove unitprice
  .replace(result["KDV"], '')  // Remove KDV
  .replace(result["productTotalPrice"], '')  // Remove productTotalPrice
  .replace(result["KAP"], '')  // Remove productTotalPrice
  .replace(result["KDVTutar"], '')  // Remove productTotalPrice
  .replaceAll("TL", '')  // Remove productTotalPrice
  .replace("tl", '')  // Remove productTotalPrice
  .replace("%", '')  // Remove productTotalPrice
  //.replace(/\s+/g, ' ').trim()
  //.replace(/\s{2,}/g, '')
  .trim();
  result.productName = productNameMatch.length > 0 
  ? productNameMatch.split(" ").some(s=>s.length>21)
  ?productNameMatch.match(/[^\d\s]{4,}/g)?.filter(word => word !== null)[0]
  :productNameMatch
  : null;
  result.billType=billType;
  
  return result;

}



  const tableFinder=(arr)=>{
    console.log("orjinal text",arr)
    const filteredLinesFirstLayer = arr.filter(line =>
        !allPossible.concat(isimler).some(word => line.toLowerCase()?.includes(word.toLowerCase()))
        //!allPossible.concat(iller).concat(isimler).some(word => line.toLowerCase()?.includes(word.toLowerCase()))
      );
      console.log("first Layer",filteredLinesFirstLayer)
      const concattedFirstLayer = [].concat.apply([], filteredLinesFirstLayer.map(line => line.split(/\s+/)));
      console.log("first Layer birleştirilen",concattedFirstLayer)

      const longerLines=concattedFirstLayer.filter(l=>String(l).length>25)
      const filteredLinesSecondLayer = concattedFirstLayer.filter(line =>
        
          !allPossibleSecondLayer.some(word => line.toLowerCase()?.includes(word.toLowerCase()))
        
      ).filter(word => isNaN(parseInt(word, 10))).concat(longerLines);

      console.log("second Layer",filteredLinesSecondLayer)

      const possibleProductArray = ["bedeli","Adet","birim","TL","Ad","BR","Bedeli"];
      const filteredLinesThirdLayer = filteredLinesSecondLayer.filter(prefix =>
        arr.some(item =>
          item.includes(prefix) && possibleProductArray.some(element => item.includes(element))
        )
      );
      console.log("third Layer",filteredLinesThirdLayer)

      const filteredLinesForthLayer = arr.filter(prefix =>
        filteredLinesThirdLayer.some(item =>
          prefix.includes(item)
        )
      ).filter(line => !containsConsecutiveAvoidWords(avoidnumberWords,line)).filter(line => !containsConsecutiveAvoidWords(avoidtableHeader,line));

      const resultArray = filteredLinesForthLayer.map(line => extractInfo(line));

      return {Mal_Hizmet_json:filteredLinesForthLayer,table:resultArray}

  }
  
  console.log("Ürün Listesi:", tableFinder(pdfTry1));

